### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1277: ordinal not in range(128)

### ISSUE THREAD

**Issue by charls-a** [sfan5/pytgbridge#10]
Telegram@servidor:~/pytgbridge$ ./pytgbridge
Traceback (most recent call last):
  File "./pytgbridge", line 86, in <module>
    main(configpath, loglevel)
  File "./pytgbridge", line 46, in main
    config = parse_config(configpath)
  File "./pytgbridge", line 29, in parse_config
    s = f.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1277: ordinal not in range(128)

**Comment by sfan5** [comment]
Either make sure there are no foreign (ASCII-only) characters in your configuration or configure your Python environment to default to UTF-8, as any modern environment should.
