### ISSUE TITLE
Problem . any fix?

### ISSUE THREAD

**Issue by Konraditow** [sfan5/pytgbridge#12]
53219 pts/0    Sl     0:00 python3 ./pytgbridge -q -D
  53223 pts/0    R+     0:00 ps -x
marvel@Konrado:~/pytgbridge$ [2022-07-12 20:51:08] Exception in IRC event handler
Traceback (most recent call last):
  File "/home/marvel/pytgbridge/src/irc.py", line 27, in _invoke_event_handler
    self.event_handlers[name](*args, **kwargs)
  File "/home/marvel/pytgbridge/src/bridge.py", line 241, in wrap
    func(l, event, *args)
  File "/home/marvel/pytgbridge/src/bridge.py", line 320, in irc_message
    self.tg.send_message(l.telegram, msg, parse_mode="HTML")
  File "/home/marvel/pytgbridge/src/telegram.py", line 207, in send_message
    self.bot.send_message(chat_id, text, **kwargs)
  File "/home/marvel/.local/lib/python3.9/site-packages/telebot/__init__.py", line 1006, in send_message
    apihelper.send_message(
  File "/home/marvel/.local/lib/python3.9/site-packages/telebot/apihelper.py", line 267, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/home/marvel/.local/lib/python3.9/site-packages/telebot/apihelper.py", line 152, in _make_request
    json_result = _check_result(method_name, result)
  File "/home/marvel/.local/lib/python3.9/site-packages/telebot/apihelper.py", line 179, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found

**Comment by Konraditow** [comment]
I have put everything in order. the bot enters but it does not send anything to telegram and therefore nothing is sent to irc. It is seen that the irc does its job but not telegram.

**Comment by sfan5** [comment]
You probably have the ID of the chat defined incorrectly in config.json.
