### ISSUE TITLE
pylink 3.0 crashes on inspircd3

### ISSUE THREAD

**Issue by radmx** [sfan5/pytgbridge#7]
I have pylink 3 on inspircd 3 configure properly even with the target insp3 but crashes all time because of this:

[ERROR] (mynet) Caught error in handle_events, disconnecting!
Traceback (most recent call last):
 File "/usr/local/lib/python3.5/dist-packages/pylinkirc-3.0.0-py3.5.egg/pylinkirc/classes.py", line 2026, in parse_irc_command
   hook_args = self.handle_events(line)
 File "/usr/local/lib/python3.5/dist-packages/pylinkirc-3.0.0-py3.5.egg/pylinkirc/protocols/ircs2s_common.py", line 356, in handle_events
 parsed_args = func(sender, command, args)
 File "/usr/local/lib/python3.5/dist-packages/pylinkirc-3.0.0-py3.5.egg/pylinkirc/protocols/ircs2s_common.py", line 690, in handle_quit
return {'text': args[0], 'userdata': userdata}
IndexError: list index out of range

and i see a shell output:
2021-02-11 14:48:04,419 [ERROR] (chat) The offending line was: <- :00BAAAAAY QUIT 

why is this for ?? and how to avoid it, ???

**Comment by sfan5** [comment]
This project has nothing to do with pylinkirc. Why are you posting this here?

**Comment by radmx** [comment]
omg, please accept my apologies! wrong git!
