### ISSUE TITLE
"SyntaxError: invalid syntax" during exec

### ISSUE THREAD

**Issue by charls-a** [sfan5/pytgbridge#9]
Telegram@servidor:~/pytgbridge$ ./pytgbridge 
Traceback (most recent call last): 
  File "./pytgbridge", line 9, in <module> 
    from src.telegram import TelegramClient 
  File "/home/Telegram/pytgbridge/src/telegram.py", line 1, in <module> 
    import telebot 
  File "/home/Telegram/.local/lib/python3.5/site-packages/telebot/__init__.py", line 459 
    e.args = e.args + (f'Typed middleware handler "{typed_middleware_handler.__qualname__}"',) 
                                                                                           ^ 
SyntaxError: invalid syntax

**Comment by sfan5** [comment]
The error happens inside pyTelegramBotAPI, my code has nothing to do with this.
I can tell you why it happens though: Format strings like that are only supported in Python 3.6 so you simply need to upgrade.
